application: google.com:leagueofinterns
version: 1
runtime: python
api_version: 1
threadsafe: yes

env_variables:
  # If true, show the title of the current game on the UI
  show_game_title: false
  # Maximum number of players per game
  max_players: 200

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: assets/images
- url: /js
  static_dir: assets/js
- url: /stylesheets
  static_dir: assets/stylesheets

- url: /admin/.*
  script: main.py
  login: admin
  auth_fail_action: unauthorized

- url: /appeng/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py
  login: required
  auth_fail_action: redirect
