application: google.com:leagueofinterns
version: 2
runtime: python
api_version: 1
threadsafe: yes

# Accessed with os.environ in App Engine
env_variables:
  # The default game_name to use when no game_name param is given
  default_game_name: MTV

  # The name of the app (Eg. "League of Interns")
  global_name: League of Interns
  # The header desc (Eg. "An internal assassins game")
  global_desc: |
    An internal <a href="http://en.wikipedia.org/wiki/Assassin_(game)">assassins</a>
    game for the summer MTV interns of 2012
  # The body desc (Eg. "Pick up your weapon from Bob")
  short_desc: |
    Please review the rules below, pick up your weapon from <b>MTV-43-132</b>,
    and wait for your first target!
  # Show the internal title of the current game (eg. 'MTV') on the UI.
  show_game_title: false
  # Show the JS countdown timer
  show_countdown: true
  # Show general game stats
  show_stats: true
  # Show leaderboard
  show_leaderboard: true
  # Emails for the Contact Us link
  contact_emails: billycao+league@google.com,nsolichin+league@google.com,shiryehoshua+league@google.com,tinaroh+league@google.com

  # Maximum number of players per game
  max_players: 200
  # Time zones are in ISO 8601, eg.'2013-01-01T00:00-07:00' is midnight morning of New Year, 2013, Pacific Time
  # Note js countdown widget has a max range of 99 days
  time_registration_ends: 2013-01-01T00:00-07:00
  time_game_begins: 2013-01-01T00:00-07:00
  time_game_ends: 2013-01-02T00:00-07:00

  # Allow suicides (entering your own kill code)
  allow_suicide: true
  # Activate the public hitlist
  public_hitlist: false
  # Max number of players to put on the hitlist
  num_histlist: 20

  # Send email to players upon start
  send_start_email: true
  # Sender of start_email. This must be an admin email
  start_email_sender: "League of Interns <billycao@google.com>"
  # HTML email to send to players when the game begins, %s = game_name
  start_email_body: |
    Thanks for joining the <a href="https://leagueofinterns.googleplex.com/?game_name=%s">League of Interns</a>!<br />
    <br />
    <b>The games have begun</b>!<br />
    <br />
    Check the site for your first target, updated rules/FAQ, and your kill code (remember it!).<br />
    <br />
    If you haven't yet, pick up your weapon from MTV-43-132!<br />
    <br />
    --- <br />
    <br />
    Important note: The boat cruise tonight is fair game for all. Indoors/outdoors no one is safe on the boat!<br />
    <br />
    Also remember that otherwise the no indoors rule is strict. This includes indoor cafes.<br />
    <br />
    An extra note: The two planners with database access (billycao@ and nsolichin@) have chosen to exempt ourselves from being able to win prizes in the interest of fairness. We'll still play, we just cant win.<br />We'll only tamper with the database if something goes wrong and manual editing is required.<br />
    <br />
    Be ninja, play fair, and <b>good luck</b>!<br />
    ---<br />
    <br />
    This message was automatically generated by League of Interns. Problems? Let us know!<br />
    <br />
    Don't worry, we won't spam you. Future email notifications will be opt-out.<br />

handlers:
# Favicon
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Statics
- url: /images
  static_dir: assets/images
- url: /js
  static_dir: assets/js
- url: /stylesheets
  static_dir: assets/stylesheets

# App Engine Dashboard
- url: /appeng/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

# Admin
- url: /admin/.*
  script: main.py
  login: admin
  auth_fail_action: unauthorized

- url: .*
  script: main.py
  login: required
  auth_fail_action: redirect
