#!/usr/bin/env python

import os
from random import shuffle

from google.appengine.api import urlfetch
from google.appengine.ext.webapp import template
from google.appengine.api import users, mail
from google.appengine.ext import webapp
from models import *

class CreateGame(webapp.RequestHandler):
  def get(self):
    game_name = self.request.get('game_name')
    if db.get(game_key(game_name or 'default_game')):
      self.response.out.write("Exists")
      return
    game = Game(key_name=game_name or 'default_game')
    game.put()
    self.response.out.write("Created")
	
class EndGame(webapp.RequestHandler):
  def get(self):
    game_name = self.request.get('game_name')
    missions = Mission.in_game(game_name).fetch(None)
    db.delete(missions)
    self.response.out.write("Done")

class StartGame(webapp.RequestHandler):
  def get(self):
    game_name = self.request.get('game_name')
    if Game.has_started(game_name):
      self.response.out.write("Already started")
      return

    users = Player.in_game(game_name).fetch(None)
    shuffle(users)

    assassin = users[len(users) - 1]
    for user in users:
      mission = Mission(parent=game_key(game_name))
      mission.assassin = assassin.nickname
      mission.victim = user.nickname
      mission.put()
      assassin = user
      # Send email to all players
      if not mail.is_email_valid(user.email):
        self.response.out.write("Warning: Invalid email: " + user.email)
      else:
        sender_address = "League of Interns <billycao@google.com>"
        subject = "[League of Interns] Let the games begin!"
        body = """
Thanks for joining the League of Interns!

The games have begun!

Check the site for your first target, updated rules/FAQ, and your kill code (remember it!).

Be ninja, play fair, and good luck!

---

This message was automatically generated by League of Interns. Problems? Let us know!

Don't worry, we won't spam you. Future email notifications will be opt-out.
"""
        html = """
Thanks for joining the <a href="https://leagueofinterns.googleplex.com">League of Interns</a>!<br />
<br />
<b>The games have begun</b>!<br />
<br />
Check the site for your first target, updated rules/FAQ, and your kill code (remember it!).<br />
<br />
Be ninja, play fair, and <b>good luck</b>!<br />
<br />
---<br />
<br />
This message was automatically generated by League of Interns. Problems? Let us know!<br />
"""
        mail.send_mail(sender_address, user.email, subject, body, html=html)
    self.response.out.write("Done")
    
